#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted at the root of a domain.
# `domain` is used to generate absolute URLs. (required to generate a valid feed)
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com
base_url: /
domain: mynt.mirroredwhite.com


#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: Andrew Fricke
# A description of your site to be used in header meta tags.
description:
# Used in the site feed.
email: andrew@mirroredwhite.com
# Your site's subtitle.
subtitle: static done simple
# Your site's title. (required to generate a valid feed)
title: mynt


#
# THIRD PARTY SETTINGS
#

# If you'd like to enable Google Analytics for your site, set this to your tracking code.
analytics: UA-27967356-1


#
# Chances are you probably don't need to touch anything below here.
#

archive_layout: archive.html
archives_url: /news/archives/
posts_url: /news/<year>/<month>/<day>/<title>/
tag_layout: tag.html
tags_url: /news/archives/
